version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt or requirements-dev.txt
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly
      day: "monday"
      time: "08:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
