# In Linux, the /mount directory (often written as /mnt) is used as a mount point — a place in the directory tree where additional file
# systems can be attached (or "mounted") to the main file system. Let's clarify:
# What is a Mount Point?
#   - In Linux, everything is a file, and everything exists in a single directory tree starting from / (the root).
#   - To access other storage devices (USB drives, partitions, remote shares), they must be "mounted" into this tree.
#   - A mount point is simply a directory (like /mnt/usb) where the contents of another file system appear after being mounted.
services:
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./load_tests/:/mnt/locust
    command: -f /mnt/locust/loadtest.py
    networks:
      - monitoring
    restart: unless-stopped
    read_only: true

  locust-metrics-exporter:
    image: containersol/locust_exporter
    ports:
      - "9646:9646"
    environment:
      - LOCUST_EXPORTER_URI=http://locust:8089
    depends_on:
      - locust
    networks:
      - monitoring
    restart: unless-stopped
    read_only: true

#   ./prometheus.yml → a config file on your host (relative to the Compose file).
#     - It’s mounted inside the container at /etc/prometheus/prometheus.yml.
#     - The command: line overrides the default command and tells Prometheus to use this file.
#     - Prometheus reads this file to know:
#     - What targets to scrape
#     - What rules to load
#     - How to label and store metrics

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    restart: unless-stopped
    read_only: true

#   Docker creates a named volume called grafana_data (stored in /var/lib/docker/volumes/grafana_data/_data on the host).
#     This volume is mounted into the container at /var/lib/grafana, where Grafana stores its:
#           - Dashboards
#           - User settings
#           - Plugins
#           - Database
#     This makes your data persistent — it survives container restarts, rebuilds, or even deletions.

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./Dashboard/loadstream.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro
      - ./Dashboard/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./Dashboard/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    environment:
      - GF_SECURITY_ADMIN=${GF_SECURITY_ADMIN:-admin}
      - GF_SECURITY_PASSWORD=${GF_SECURITY_PASSWORD:-admin}
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped
    read_only: true

volumes:
  grafana_data:

networks:
  monitoring:
    driver: bridge
