name: Security Checks

on:
  push:
    branches: [enhancements]
  pull_request:
    branches: [main]

jobs:
  docker-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy on Docker Compose images
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          scan-type: 'config'
          scan-ref: 'docker-compose.yml'

  python-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit on load_tests
        run: bandit -r ./load_tests
