name: Update Dependencies

on:
  schedule:
    # Run weekly on Monday at 8 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-python-deps:
    name: Update Python Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update Python dependencies
      run: |
        # Create a temporary requirements.in file from requirements-dev.txt
        sed 's/==.*//' requirements-dev.txt > requirements.in

        # Update to latest versions
        pip-compile --upgrade requirements.in --output-file requirements-dev.txt

        rm requirements.in

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update Python dependencies"
        title: "🔄 Update Python Dependencies"
        body: |
          ## 🔄 Automated Dependency Update

          This PR updates Python dependencies to their latest versions.

          ### What's Changed
          - Updated Python dependencies in `requirements-dev.txt`

          ### Testing
          - [ ] All linters pass
          - [ ] Security scans pass
          - [ ] No breaking changes detected

          **Auto-generated by GitHub Actions** 🤖
        branch: update-python-dependencies
        delete-branch: true

  update-actions:
    name: Update GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update GitHub Actions versions
      uses: upgradeworld/update-github-actions@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update GitHub Actions versions"
        title: "🔄 Update GitHub Actions"
        body: |
          ## 🔄 Automated GitHub Actions Update

          This PR updates GitHub Actions to their latest versions.

          ### What's Changed
          - Updated action versions in workflow files

          **Auto-generated by GitHub Actions** 🤖
        branch: update-github-actions
        delete-branch: true
